version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - 8080:8080
    # para poder scale
    expose:
      - "8080"
    depends_on:
      - lb
      - dbmongo
    restart: always # Si el container falla se reinicia
  dbmongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # Por defecto se crea un user para base de datos admin
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  lb:
    image: nginx
    volumes:
     - ./proxy.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always